/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HeightPredictor;

/**
 *
 * @author ADMIN
 */
public class main extends javax.swing.JFrame {
public double Father = 0.0d, Mother = 0.0d, Result = 0.0d;
    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        height1 = new javax.swing.JTextField();
        height2 = new javax.swing.JTextField();
        output = new javax.swing.JLabel();
        enter = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        boy = new javax.swing.JRadioButton();
        girl = new javax.swing.JRadioButton();
        gender = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Father");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 255));
        jLabel2.setText("Mother");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));
        getContentPane().add(height1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 141, -1));
        getContentPane().add(height2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 141, -1));

        output.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        output.setForeground(new java.awt.Color(255, 51, 51));
        output.setText("               Result");
        output.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(output, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 164, 47));

        enter.setBackground(new java.awt.Color(102, 255, 51));
        enter.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        enter.setText("ENTER");
        enter.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.green, java.awt.Color.gray));
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });
        getContentPane().add(enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 74, -1));

        clear.setBackground(new java.awt.Color(255, 51, 51));
        clear.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        clear.setText("CLEAR");
        clear.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 51, 102), null));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        boy.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        boy.setForeground(new java.awt.Color(51, 102, 255));
        boy.setText("Boy");
        boy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boyActionPerformed(evt);
            }
        });
        getContentPane().add(boy, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        girl.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        girl.setForeground(new java.awt.Color(255, 102, 255));
        girl.setText("Girl");
        getContentPane().add(girl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        gender.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        gender.setForeground(new java.awt.Color(255, 153, 0));
        gender.setText("Child Gender");
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 97, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 12)); // NOI18N
        jLabel3.setText("Height Value");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("1 inch  = 2.54 cm");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, 31));

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("NOTE: Use CM upon entering value");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setText("HUMAN HEIGHT PREDICTOR");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -10, 220, 80));

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("1 foot  = 30.48 cm");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        height1.setText("");
         height2.setText("");
         output.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void boyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boyActionPerformed

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
       Father = Double.parseDouble(height1.getText());
       Mother = Double.parseDouble(height2.getText());
       
       if (boy.isSelected()){
           Result = Father + Mother + 13; 
           Result = Result / 2;
           output.setText(Result + "cm");
       }   
           if (girl.isSelected()){
              Result = Father + Mother - 13; 
           Result = Result / 2;
              output.setText(Result + "cm");
           
       }
        
    }//GEN-LAST:event_enterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton boy;
    private javax.swing.JButton clear;
    private javax.swing.JButton enter;
    private javax.swing.JLabel gender;
    private javax.swing.JRadioButton girl;
    private javax.swing.JTextField height1;
    private javax.swing.JTextField height2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel output;
    // End of variables declaration//GEN-END:variables
}
